Testsuite: model.common.SerializableTest
Tests run: 0, Failures: 0, Errors: 1, Time elapsed: 0.039 sec

Testcase: model.common.SerializableTest took 0 sec
	Caused an ERROR
null
java.lang.NullPointerException
	at model.storage.StorageManager.getAppropriateDAO(StorageManager.java:38)
	at model.productcontainer.StorageUnitVault.saveNew(StorageUnitVault.java:108)
	at model.productcontainer.StorageUnit.save(StorageUnit.java:62)
	at model.common.SerializableTest.setUpBeforeClass(SerializableTest.java:28)

